### PR TITLE
Fix testing structure

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I'm going to go ahead and tag now. The only remaining issue seems to be v1.0 on Mac (only Mac) which seems to be finding a build error.

https://travis-ci.org/rveltz/LSODA.jl/jobs/423071259

Maybe that's what you're experiencing? When I installed locally this happened the first call but not the second, which seems to be something related to BinDeps.

**Comment by rveltz** [comment]
No I experience something different:

```julia
pkg> add LSODA
 Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
  [7f56f5a3] + LSODA v0.3.0
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]
``` 

and then:

```julia
 using LSODA
[ Info: Precompiling LSODA [7f56f5a3-f504-529b-bc02-0b1fe5e64312]
ERROR: LoadError: syntax: extra token "lsoda" after end of expression
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include(::Module, ::String) at ./sysimg.jl:29
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:319 [inlined]
 [6] eval(::Expr) at ./client.jl:389
 [7] top-level scope at ./none:3
in expression starting at /Users/rveltz/.julia/packages/LSODA/qwAb/src/LSODA.jl:19
```

**Comment by ChrisRackauckas** [comment]
`LSODA v0.3.0`. Just tagged v0.4.0

**Comment by rveltz** [comment]
I know! But why

```julia
(v1.0) pkg> add LSODA@0.4
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package LSODA [7f56f5a3]:
 LSODA [7f56f5a3] log:
 ├─possible versions are: [0.0.1, 0.1.0, 0.2.0-0.2.1, 0.3.0] or uninstalled
 └─restricted to versions 0.4 by an explicit requirement — no versions left

(v1.0) pkg> add LSODA#master
   Cloning git-repo `https://github.com/rveltz/LSODA.jl.git`
  Updating git-repo `https://github.com/rveltz/LSODA.jl.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
  [7f56f5a3] + LSODA v0.3.0+ #master (https://github.com/rveltz/LSODA.jl.git)
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [7f56f5a3] + LSODA v0.3.0+ #master (https://github.com/rveltz/LSODA.jl.git)
  Building LSODA → `~/.julia/packages/LSODA/TRqQp/deps/build.log`

```

**Comment by ChrisRackauckas** [comment]
It's not in yet: https://github.com/JuliaLang/METADATA.jl/pull/17563

**Pull request merged**
