### PR TITLE
correct the test structure

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This was merged too early. It seems the tests failed?

**Comment by rveltz** [comment]
The test now pass but on my computer I cant even load `LSODA`. The precompilation failed as shown above as if `Pkg3` downloads the wrong version.

**Comment by ChrisRackauckas** [comment]
This hasn't been tagged yet.

**Comment by ChrisRackauckas** [comment]
You need to install via `]dev LSODA` or tag this. I'll tag this when tests pass, but the AppVeyor script is messed up somehow.

**Pull request merged**
