### PR TITLE
update common interface

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
This updates the common interface to the new specs for DiffEqBase.jl's v0.15.0. It is incompatible with previous versions.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I'm not sure what that load path stuff was in the tests, but that was required to be removed for tests to pass, and definitely would be required on CI.

**Comment by ChrisRackauckas** [comment]
Cool. Tests pass. Would you be fine with a release after merging? I think there may be a nonlocality bug in the package resolver which is having LSODA cause some issues:

https://discourse.julialang.org/t/differentialequations-pkg-wont-be-added/3194/22

**Comment by rveltz** [comment]
For the tag, I am OK if it can help you.

**Comment by ChrisRackauckas** [comment]
Cool thanks. Do you want me to tag or do you want to do it?

**Comment by rveltz** [comment]
Please do it, I have never done it.

Thank you.

**Comment by ChrisRackauckas** [comment]
The METADATA PR is in. https://github.com/JuliaLang/METADATA.jl/pull/8847

Note that I will likely have another PR come in by the end of the week. It will be a small PR to the common interface which will just modify the type that things are saved to. That will be the last change for DifferentialEquations.jl ecosystem version 2.0, and so things will go stable again (I just wanted all of the changes in before the JuliaCon workshop!)

**Pull request merged**
