### PR TITLE
update common interface

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
This updates the common interface to the new specs for DiffEqBase.jl's v0.15.0. It is incompatible with previous versions. This should not be merged until DiffEqBase.jl v0.15.0 is released, and upper bounds are placed in METADATA.

### CODE REVIEW

**Comment by rveltz** [comment]
I am in the process of removing returning the context. Did you see that lsoda returns a single argument now?

**Comment by ChrisRackauckas** [comment]
>I am in the process of removing returning the context. Did you see that lsoda returns a single argument now?

No I didn't. This is built from a branch that's a bit behind on the times. I can wait a bit before updating this branch. This is one PR part of a huge API re-standardization so I'm completing that before coming back to this.

**Comment by ChrisRackauckas** [comment]
Updated to master. This should work when DiffEqBase v0.15.0 merges. Can we get a merge + tag then sometime tomorrow to match 

https://github.com/JuliaLang/METADATA.jl/pull/8769#issuecomment-293639490

Otherwise having LSODA could cause update issues.

**Comment by ChrisRackauckas** [comment]
Tests were passing locally, but seem to fail in test 2 on Travis. Is master failing?

Note that due to version bounds, until this is tagged, having LSODA will downgrade all of DifferentialEquations.jl due to the API update. No need to rush (LSODA.jl is compatible but not part of the main distribution, so it shouldn't be a problem in the vast majority of cases) but if you think the fix will take awhile, it might be good to split that to a feature branch and tag a version with this.

**Comment by ChrisRackauckas** [comment]
Updated to current master... is the master branch broken?

**Comment by rveltz** [comment]
Strange... `lsoda_create_ctx` should not be called on master, only in the other branch `branch-allocations-on-C-side`. Are you on the master?

**Comment by ChrisRackauckas** [comment]
Oh, I meant I updated it to `branch-allocations-on-C-side`. Isn't this the branch you're merging to master soon?

**Comment by rveltz** [comment]
I am not sure. If the solution of the master works (as it seems to be), it is simpler than the other branch . Hence, I would keep the master.

The issue seems to come from `AbstractODEProblem`. Isn't it your library?

**Comment by ChrisRackauckas** [comment]
>The issue seems to come from AbstractODEProblem. Isn't it your library?

Yes, it's due to an update in DiffEqBase.jl, and is why this PR is here. I'll make this even with master.

**Pull request closed without merging**
